distributor/distributor/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.homepage, name='homepage'),

    path('repository/', include('repository.urls')),
    path('financial-accounting/', include('financial_accounting.urls')),
    path('local-business/', include('local_business.urls')),
    path('user/', include('user.urls')),
]

distributor/user/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('logout', views.user_logout_view, name='user-logout'),

    path('dealership-registration/', views.dealership_registration_view, name='dealership-registration'),
    path('dropdown/', views.load_districts, name='ajax-load-districts'),

    path('dealerships/', views.dealerships_of_current_user, name='dealerships-of-current-user'),
    path('dealerships-in-queue/', views.dealerships_in_queue_of_current_user,
         name='dealerships-in-queue-of-current-user'),
    path('dealerships/<str:dealership_id>/', views.update_delete_dealership_information_view,
         name='update-dealership-information'),
]

distributor/dealership/models.py
from django.db import models


class City(models.Model):
    id = models.CharField(primary_key=True, max_length=4, editable=False)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class District(models.Model):
    id = models.CharField(primary_key=True, editable=False, max_length=3)
    name = models.CharField(max_length=50)
    city = models.ForeignKey(City, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.name


class DealershipType(models.Model):
    id = models.CharField(primary_key=True, max_length=2, editable=None)
    name = models.CharField(max_length=10)
    maximum_number_of_dealerships = models.IntegerField()
    maximum_debt = models.IntegerField(default=0)
    discount_rate = models.FloatField(default=0.0)

    def __str__(self):
        return self.name


class Owner(models.Model):
    name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=15)
    email = models.CharField(max_length=320)

    def __str__(self):
        return self.name


class Dealership(models.Model):
    id = models.CharField(primary_key=True, editable=False, max_length=9)
    name = models.CharField(max_length=100)
    type = models.ForeignKey(DealershipType, max_length=2, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True, blank=True)
    district = models.ForeignKey(District, on_delete=models.CASCADE, default=None)
    address = models.CharField(max_length=200)
    registration_date = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    debt = models.IntegerField(default=0)
    is_active = models.BooleanField(default=True)

    # Customizing id
    def save(self, *args, **kwargs):
        if self.type.id == 'DQ':
            max_number_of_dealerships = self.type.maximum_number_of_dealerships
        else:
            max_number_of_dealerships = self.type.maximum_number_of_dealerships

        for i in range(1, max_number_of_dealerships + 1):
            available_dealership_id = Dealership.objects.filter(
                id=f'{self.city.id}{self.district.id}{self.type.id}{i}'
            ).count()
            if available_dealership_id == 0:
                self.id = f'{self.city.id}{self.district.id}{self.type.id}{i}'
                break
        super(Dealership, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

distributor/user/models.py
from django.db import models

# Create your models here.

distributor/user/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from dealership.models import District, Dealership


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Xác nhận mật khẩu', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'username',
            'last_name',
            'first_name',
            'email',
            'password1',
            'password2'
        )
        help_texts = {
            'username': None,
        }
        labels = {
            'username': 'Tên tài khoản',
            'first_name': 'Tên',
            'last_name': 'Họ',
        }

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class UserLoginForm(forms.ModelForm):
    username = forms.CharField(max_length=100, label='Tên đăng nhập')
    password = forms.CharField(max_length=100, label='Mât khẩu', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'username',
            'password'
        )


class DealershipRegistrationForm(forms.ModelForm):

    owner_phone = forms.CharField(max_length=15, label='Số điện thoại người đăng ký')

    class Meta:
        model = Dealership
        fields = (
            'name',
            'type',
            'city',
            'district',
            'address',
            'owner_phone'
        )
        labels = {
            'name': 'Tên đại lý',
            'type': 'Loại đại lý',
            'city': 'Thành phố / Tỉnh',
            'district': 'Quận / Phường',
            'address': 'Địa chỉ',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['district'].queryset = District.objects.none()

        if 'city' in self.data:
            try:
                city_id = self.data.get('city')
                print(city_id)
                self.fields['district'].queryset = \
                    District.objects.filter(city_id=city_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['district'].queryset = self.instance.city\
                .district_set.order_by('name')

distributor/user/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from user.forms import DealershipRegistrationForm
from dealership.models import Dealership, District
from local_business.models import DealershipRegistrationQueue, DealershipCancellationQueue


def user_logout_view(request):
    logout(request)
    return redirect('/')


def get_user_fullname(request):
    return f'{request.user.first_name} {request.user.last_name}'


@login_required(login_url='homepage')
def dealership_registration_view(request):
    dealership_registration_form = DealershipRegistrationForm()
    context = {
        'form': dealership_registration_form,
        'username': f'{request.user.first_name} {request.user.last_name}',
    }

    if request.method == 'POST':
        filled_form = DealershipRegistrationForm(request.POST)

        if filled_form.is_valid():
            """
            Check the number of existing dealerships
            which are corresponding type
            of which user entered
            """

            dealership_type = filled_form.cleaned_data['type']
            dealership_type_id = filled_form.cleaned_data['type'].id

            dealership_district = filled_form.cleaned_data['district']

            current_number_of_dealerships_in_queue = DealershipRegistrationQueue.objects \
                .filter(district=dealership_district,
                        type=dealership_type_id,
                        is_done=False) \
                .count()
            current_number_of_dealerships = Dealership.objects \
                .filter(district=dealership_district,
                        type=dealership_type_id) \
                .count()

            """
            Check type of dealership which user entered
            Assign a maximum number of dealership in a variable
            based on dealership type user's form
            """
            max_number_of_dealerships = dealership_type.maximum_number_of_dealerships

            """
            Check whether if the number of existing dealership
            is greater than the maximum number or not
            If not generate dealership id for user
            """
            if current_number_of_dealerships_in_queue >= max_number_of_dealerships:
                new_form = filled_form
                message = f'Đã đủ số lượng đơn đăng ký đại lý loại {filled_form.cleaned_data["type"]} ' \
                          f'trên {filled_form.cleaned_data["district"]}, {filled_form.cleaned_data["city"]}!'

                messages.error(request, message)
                context['form'] = new_form
                return redirect('dealership-registration')
            elif current_number_of_dealerships >= max_number_of_dealerships:
                new_form = filled_form
                message = f'Đã đủ số lượng đại lý loại {filled_form.cleaned_data["type"]} ' \
                          f'trên {filled_form.cleaned_data["district"]}, {filled_form.cleaned_data["city"]}!'

                messages.error(request, message)
                context['form'] = new_form
                return redirect('dealership-registration')

            """
            Create new owner based on the current user logged in
            """
            dealership_type = filled_form.cleaned_data['type']
            dealership_name = filled_form.cleaned_data['name']
            dealership_city = filled_form.cleaned_data['city']
            dealership_address = filled_form.cleaned_data['address']
            dealership = DealershipRegistrationQueue(
                name=dealership_name,
                type=dealership_type,
                city=dealership_city,
                district=dealership_district,
                address=dealership_address,
                owner_name=f'{request.user.first_name} {request.user.last_name}',
                owner=request.user.pk,
                owner_phone=filled_form.cleaned_data['owner_phone'],
                owner_email=request.user.email
            )
            dealership.save()
            message = 'Đã gửi đơn đăng ký đến nhà phân phối!'

            messages.success(request, message)
            return redirect('dealership-registration')

    return render(request, 'user/dealership_registration_form.html', context)


def load_districts(request):
    city_id = request.GET['city']
    districts = District.objects.filter(city_id=city_id).all()
    return render(request, 'user/district_dropdown_list_options.html',
                  {'districts': districts})


def dealerships_of_current_user(request):
    current_user_id = request.user.pk
    dealerships_of_current_owner = Dealership.objects.filter(
        owner_id=current_user_id
    )
    context = {
        'dealerships': dealerships_of_current_owner,
        'username': get_user_fullname(request)
    }

    return render(request, 'user/dealerships_of_current_user.html', context)


def dealerships_in_queue_of_current_user(request):
    current_user_id = request.user.pk
    dealerships_in_registration_queue_of_current_owner = DealershipRegistrationQueue.objects.filter(
        owner=current_user_id, is_done=False
    )

    dealerships_in_cancellation_queue_of_current_owner = {}
    dealerships = Dealership.objects.filter(owner=current_user_id)
    for dealership in dealerships:
        dealerships_in_cancellation_queue = DealershipCancellationQueue.objects.filter(
            dealership=dealership
        )
        for each in dealerships_in_cancellation_queue:
            dealerships_in_cancellation_queue_of_current_owner[each.pk] = []
            dealerships_in_cancellation_queue_of_current_owner[each.pk] += [
                each.dealership.name,
                each.dealership.type.name,
                each.dealership.address,
                each.dealership.district.name,
                each.dealership.city.name,
                each.dealership.registration_date.strftime('%d/%m/%Y'),
                each.status,
            ]

    context = {
        'dealerships_in_registration_queue': dealerships_in_registration_queue_of_current_owner,
        'dealerships_in_cancellation_queue': dealerships_in_cancellation_queue_of_current_owner,
        'username': get_user_fullname(request)
    }

    return render(request, 'user/dealerships_in_queue_of_current_owner.html', context)


def update_delete_dealership_information_view(request, dealership_id):
    is_done = False
    try:
        dealership_id = int(dealership_id)
        dealership = DealershipRegistrationQueue.objects.get(id=dealership_id)
        update = DealershipRegistrationQueue.objects.filter(id=dealership_id)
    except ValueError:
        dealership = Dealership.objects.get(id=dealership_id)
        update = Dealership.objects.filter(id=dealership_id)
        is_done = True

    context = {
        'dealership': dealership,
        'is_done': is_done,
        'username': get_user_fullname(request)
    }

    if request.method == 'POST':
        if 'update' in request.POST:
            new_dealership_name = request.POST.get('dealership_name')
            new_dealership_address = request.POST.get('dealership_address')
            update.update(name=new_dealership_name, address=new_dealership_address)
            messages.success(request, 'Cập nhật thông tin đại lý thành công')
            return redirect('update-dealership-information', dealership_id)
        if 'cancel' in request.POST:
            if is_done:
                if dealership.debt == 0:
                    try:
                        DealershipCancellationQueue.objects.get(dealership=dealership, is_done=False)
                        messages.warning(request, 'Đơn huỷ đăng ký đại lý đã được gửi! '
                                                  'Vui lòng chờ bộ phân kinh doanh duyệt đơn')
                        return redirect('update-dealership-information', dealership_id)
                    except DealershipCancellationQueue.DoesNotExist:
                        DealershipCancellationQueue(dealership=dealership, message=request.POST.get('message')).save()
                        Dealership.objects.filter(id=dealership_id).update(is_active=False)
                        messages.success(request, 'Đã gửi đơn huỷ đăng ký đại lý cho nhà phân phối')
                        return redirect('update-dealership-information', dealership_id)
                else:
                    messages.error(request, 'Vui lòng thanh toán công nợ trước khi thực hiện huỷ đăng ký đại lý, '
                                            f'công nợ còn lại: {dealership.debt:,} VNĐ')
                    return redirect('update-dealership-information', dealership_id)

            DealershipRegistrationQueue.objects.get(id=dealership_id).delete()
            messages.success(request, 'Đã huỷ đơn đăng ký đại lý')
            return redirect('dealerships-in-queue-of-current-user')

    return render(request, 'user/edit_dealership_information.html', context)

distributor/templates/user/dealership_registration_form.html
{% extends 'home/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% include 'common/permanent_messages.html' %}

    <div id="dealership_registration_form">
        <h1>Đăng ký đại lý</h1>

        <form action="{% url 'dealership-registration' %}" method="post"
            id="dealershipRegistrationForm">
            {% csrf_token %}
            {% for field in form %}
                <div class="form_group mb-2">
                    {{ field.label_tag }}
                    {% render_field field class="form-control" %}
                </div>
            {% endfor %}
            <input type="submit" class="btn btn-primary btn-lg" value="Đăng ký">
        </form>

        <script src="{% static 'js/jquery/jquery-3.3.1.min.js' %}"></script>
        <script>
            $(document).ready(function () {
                $("#id_city").change(function () {
                    const url = '/user/dropdown';
                    const cityId = $(this).val();
                    $.ajax({
                        url: url,
                        data: {
                            'city': cityId
                        },
                        success: function (data) {
                            $("#id_district").html(data);
                        }
                    });
                });
            })
        </script>
    </div>
{% endblock %}

distributor/templates/user/dealerships_in_queue_of_current_owner.html
{% extends 'home/base.html' %}

{% block content %}
    {% include 'common/temporary_messages.html' %}

    <legend>Đơn đăng ký đại lý:</legend>
    <div style="overflow-x: auto">
        <table class="table table-bordered">
            <tr class="thead-dark">
                <th>Tên đại lý</th>
                <th>Địa chỉ</th>
                <th>Ngày đăng ký</th>
                <th>Loại</th>
                <th>Tỉnh thành</th>
                <th>Quận</th>
                <th>Trạng thái</th>
                <th>Chỉnh sửa đơn đăng ký</th>
            </tr>

            {% for dealership in dealerships_in_registration_queue %}
                <tr>
                    <td>{{ dealership.name }}</td>
                    <td>{{ dealership.address }}</td>
                    <td>{{ dealership.registration_date|date:"d/m/Y" }}</td>
                    <td>{{ dealership.type }}</td>
                    <td>{{ dealership.city }}</td>
                    <td>{{ dealership.district }}</td>
                    <td>{{ dealership.status }}</td>
                    <td>
                        <div class="row">
                            <div class="col-md-12">
                                <a class="btn btn-primary btn-block {% if dealership.is_done == True %}disabled{% endif %}"
                                   href="{% url 'update-dealership-information' dealership.pk %}">
                                    Chỉnh sửa
                                </a>
                            </div>
                        </div>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <legend>Đơn huỷ đăng ký đại lý:</legend>
    <div style="overflow-x:auto;">
        <table class="table table-bordered">
            <tr class="thead-dark">
                <th>Tên đại lý</th>
                <th>Loại</th>
                <th>Địa chỉ</th>
                <th>Quận</th>
                <th>Tỉnh thành</th>
                <th>Ngày đăng ký</th>
                <th>Trạng thái</th>
            </tr>
            {% for dealership, info in dealerships_in_cancellation_queue.items %}
                <tr>
                    {% for each in info %}
                        <td>{{ each }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

distributor/templates/user/dealerships_of_current_user.html
{% extends 'home/base.html' %}
{% load humanize %}

{% block content %}
    {% include 'common/temporary_messages.html' %}
    <h1>Danh sách đại lý của {{ username }}</h1>

    <div class="row">
        {% for dealership in dealerships %}
            <form action="" method="post" class="col-sm-4 px-2 py-2 form-group" id="myForm">
                {% csrf_token %}
                <div>
                    <div class="card">
                        <img class="card-img-top" src="https://placehold.co/600x400" alt="">
                        <div class="card-body">
                            <h5 class="card-title">{{ dealership.name }}</h5>
                            <p><b>Loại đại lý: </b>{{ dealership.type }}</p>
                            <p>
                                <b>Địa chỉ: </b>
                                {{ dealership.address }}, {{ dealership.district }}, {{ dealership.city }}
                            </p>
                            <p><b>Ngày đăng ký: </b>{{ dealership.registration_date|date:'d/m/Y' }}</p>
                            <p><b>Công nợ: </b>{{ dealership.debt|intcomma }} VND</p>

                            <a class="btn btn-outline-primary btn-block"
                                href="{% url 'update-dealership-information' dealership.id %}">
                                Chỉnh sửa
                            </a>
                        </div>
                    </div>
                </div>
            </form>
        {% endfor %}
    </div>
{% endblock %}

distributor/templates/user/district_dropdown_list_options.html
<option value="">---------</option>
{% for district in districts %}
<option value="{{ district.id }}">{{ district.name }}</option>
{% endfor %}

distributor/templates/user/edit_dealership_information.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    {% include 'common/permanent_messages.html' %}

    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="dealership_name" class="col-sm-2 col-form-label">Tên đại lý:</label>
            <div class="col-sm-10">
                <input id="dealership_name" name="dealership_name"
                       class="form-control" type="text" value="{{ dealership.name }}">
            </div>
        </div>

        <div class="form-group row">
            <label for="dealership_name" class="col-sm-2 col-form-label">Thành phố:</label>
            <div class="col-sm-10">
                <input id="dealership_name" class="form-control" type="text"
                       value="{{ dealership.city }}" readonly>
            </div>
        </div>

        <div class="form-group row">
            <label for="dealership_name" class="col-sm-2 col-form-label">Quận:</label>
            <div class="col-sm-10">
                <input id="dealership_name" class="form-control" type="text"
                       value="{{ dealership.district }}" readonly>
            </div>
        </div>

        <div class="form-group row">
            <label for="dealership_name" class="col-sm-2 col-form-label">Địa chỉ:</label>
            <div class="col-sm-10">
                <input id="dealership_name" class="form-control" type="text"
                       value="{{ dealership.address }}" name="dealership_address">
                <small class="form-text text-muted">Chỉ được điều chỉnh địa chỉ trong phạm vi quận,
                    không được điều chỉnh địa chỉ ở khu vực khác (thành phố, quận).</small>
            </div>
        </div>

        <button type="button" class="btn btn-primary btn-lg"
                style="float: right"
                data-toggle="modal"
                data-target="#confirmationEditModal">
            Cập nhật thông tin
        </button>
        <button type="button" class="btn btn-danger btn-lg"
                data-toggle="modal"
                data-target="#confirmationCancelModal">
            Huỷ đăng ký
        </button>

        <div class="modal fade" id="confirmationEditModal" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="confirmationEditModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmationEditModalLongTitle">Thông báo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h3>Bạn có chắc chắn muốn cập nhật thông tin đại lý?</h3>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
                        <input type="submit" class="btn btn-primary" name="update" value="Cập nhật"/>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="confirmationCancelModal" data-backdrop="static" tabindex="-1" role="dialog"
             aria-labelledby="confirmationCancelModalTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmationCancelModalLongTitle">Thông báo</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h3>Bạn có chắc chắn muốn huỷ đăng ký đại lý?</h3>
                        {% if is_done %}
                            <div class="form-group">
                                <label for="message">Hãy cho chúng tôi biết lý do quý khách huỷ đăng ký, xin cảm
                                    ơn!</label>
                                <textarea class="form-control" rows="5" name="message" id="message"></textarea>
                            </div>
                        {% endif %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Huỷ</button>
                        <input type="submit" class="btn btn-primary" name="cancel" value="Xác nhận huỷ đăng ký"/>
                    </div>
                </div>
            </div>
        </div>
    </form>
{% endblock %}